//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Framework {
            get {
                return ResourceManager.GetString("Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MediaEntities&gt;
        ///
        ///  &lt;Genres&gt;
        ///    &lt;genre&gt;ACID_JAZZ&lt;/genre&gt;
        ///    &lt;genre&gt;ACOUSTIC&lt;/genre&gt;
        ///
        ///    &lt;genre&gt;AMBIENT&lt;/genre&gt;
        ///    &lt;genre&gt;AMBIENT_TRANCE&lt;/genre&gt;
        ///    &lt;genre&gt;ALTERNATIVE&lt;/genre&gt;
        ///    &lt;genre&gt;ALTERNATIVE_METAL&lt;/genre&gt;
        ///    &lt;genre&gt;ALTERNATIVE_POP&lt;/genre&gt;
        ///    &lt;genre&gt;ALTERNATIVE_ROCK&lt;/genre&gt;
        ///
        ///    &lt;genre&gt;BACKTRACK&lt;/genre&gt;
        ///    &lt;genre&gt;BALAD&lt;/genre&gt;
        ///    &lt;genre&gt;BLUES&lt;/genre&gt;
        ///
        ///    &lt;genre&gt;CHILLOUT&lt;/genre&gt;
        ///    &lt;genre&gt;CLASSIC&lt;/genre&gt;
        ///    &lt;genre&gt;CLASSIC_ROCK&lt;/genre&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenreSchema {
            get {
                return ResourceManager.GetString("GenreSchema", resourceCulture);
            }
        }
    }
}
